name: vernam_cipher
description: Dart implementation of Vernam Cipher
version: 1.0.0
 repository: https://github.com/fingerart/vernam_cipher.git

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
