name: vernam_cipher
description: Dart implementation of Vernam Cipher
version: 1.0.0+1
repository: https://github.com/fingerart/vernam_cipher

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  crypto: ^3.0.3
  lints: ^2.0.0
  test: ^1.21.0
